### ISSUE TITLE
trace output "Not direct"

### ISSUE THREAD

**Issue by tomvoros** [maxl0rd/standingwave3#12]
When audio is playing I see the text "Not direct" printed to the output window repeatedly.  Does this indicate something is wrong?  The audio sounds fine.  Is this maybe some stray debugging text that should be removed?

Thanks in advance.

**Comment by maxl0rd** [comment]
Yes, this was a debug trace that should have been purged. There is no error in that state. I was just fixing another bug so I removed this.

**Comment by tomvoros** [comment]
Thanks for the quick fix.  Keep up the great work!
