### ISSUE TITLE
ListPerformance with elements overlapping in time not working correctly

### ISSUE THREAD

**Issue by donpark** [maxl0rd/standingwave3#3]
Are ListPerformance elements allowed to overlap in time? Following code produces sound as expected in StandingWave2 but not in StandingWave3 (creates buzzing noise during overlapped parts).

```
    sequence1.addSourceAt(tempo.beatsInSeconds(0),
            new SineSource(new AudioDescriptor(), tempo.beatsInSeconds(2), 440));
    sequence1.addSourceAt(tempo.beatsInSeconds(1),
            new SineSource(new AudioDescriptor(), tempo.beatsInSeconds(2), 660));
    sequence1.addSourceAt(tempo.beatsInSeconds(2),
            new SineSource(new AudioDescriptor(), tempo.beatsInSeconds(2), 880));
```

tempo is just a utility class that converts to # of beats to seconds. BPM was set to 140.

**Comment by maxl0rd** [comment]
Hi

That buzzing noise is probably clipping. SineSources come out full scale.

Just turn the gain down in the AudioPerformer with the mixGain property, which is mixing loss in decibels. 

ie   audioPerformer.mixGain = -12  ... would let you mix 4 sources without clipping.

That's a new SW3 feature.

**Comment by donpark** [comment]
Yup. That was it. I should have checked that first but StandingWave2 not having the problem mislead me. Thanks.
