### ISSUE TITLE
sw3 missing EnvelopeFilter?

### ISSUE THREAD

**Issue by cnanders** [maxl0rd/standingwave3#4]
First of all, I think it is absolutely incredible that someone is contributing to Joe's SW platform, so major kudos for that.  

I have SW2 integrated into a music app and am hoping to migrate to SW3 and use your nifty alchemy speed improvement.  Today I downloaded the SW3 source.  On compile with the SW3 platform (CS5 if you're interested), I immediately noticed an error where I try to define an EnvelopeFilter.  On closer inspection through the new SW3 src folder, I noticed there is no EnvelopeFilter.  All of the online documentation shows it should be there.

Is this some oversight on my part?  Was the EnvelopeFilter replaced by something else?  Any info would help.

**Comment by maxl0rd** [comment]
For future reference ... AttackFilter and Decay Filter are the preferred replacements.

**Comment by maxl0rd** [comment]
Closing
