### ISSUE TITLE
Problem with mixing simultaneous sources

### ISSUE THREAD

**Issue by dannycorts** [maxl0rd/standingwave3#5]
Hello, thanks by SW3, I am studing the new version of SW, and i am very happy with SW3.

I have found a problem with mixing simultaneous sources, for example:

```
            var sequence:ListPerformance = new ListPerformance();
            sequence.addSourceAt(0, new SineSource(new AudioDescriptor(), 0.8, 440));
            sequence.addSourceAt(0, new SineSource(new AudioDescriptor(), 0.8, 660));
            sequence.addSourceAt(0, new SineSource(new AudioDescriptor(), 0.8, 880));
            var source:IAudioSource = new AudioPerformer(sequence, new AudioDescriptor() );
            player.play(source);
```

The result have some noise, and do not work well, i whish to know how to solve this problem, do i have something wrong in my code?

Thanks by help, :)

**Comment by maxl0rd** [comment]
Hi

You're clipping. 

Just turn the gain down in the AudioPerformer with the mixGain property, which sets mixing loss in decibels.

ie audioPerformer.mixGain = -12 ... would let you mix any 4 sources without clipping.

That's a new SW3 feature.

**Comment by dannycorts** [comment]
Hey, i found that changing audioPermorfer.mixGain help to solve the problem, but i will like to know if there is a function that calculate the correct value of the mixGain, because it is not the same if the number of mixed notes change.

**Comment by maxl0rd** [comment]
That's not an easy problem to solve generally in real-time. Best to set your mix conservatively or provide a user control.

If you have a final, rendered sample that you want to be amplified to full scale, you can use sample.normalize(), but you can't use that in a real-time signal chain.

**Comment by dannycorts** [comment]
Thank you :)
